# -*- coding: utf-8 -*-
"""UAS_DAA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hc6vR9HUXQjUsWabaE2YYzzv5y7TgbBR
"""

import pandas as pd
import datetime

def tampilan(namaBarang, tanggal, sisaHari, namaPemilik):   
    df = pd.DataFrame([])
    df.insert(loc = 0, column = "Nama Barang", value = namaBarang)
    df.insert(loc = 1, column = "Tanggal", value = tanggal)
    df.insert(loc = 2, column = "Sisa Hari", value = sisaHari)
    df.insert(loc = 3, column = "Nama Pemilik", value = namaPemilik)
    df
    print(df)
    
    verifikasi = input("\nApa ingin melihat 3 teratas? [y/n] : ")
    if verifikasi == "y":
        print(df.head(3))
    elif verifikasi == "n":
        return    
    else :
        print("\nInput Salah!")
        tampilan(namaBarang, tanggal, sisaHari, namaPemilik)

def tanggalAscending(namaBarang, tanggal, sisaHari, namaPemilik):
    for i in range(0, len(tanggal)) :
        min = i
        for j in range (i, len(tanggal)) :
            if tanggal[min] > tanggal[j] :
                min = j
            tanggal[i], tanggal[min] = tanggal[min], tanggal[i]
            namaBarang[i], namaBarang[min] = namaBarang[min], namaBarang[i]
            sisaHari[i], sisaHari[min] = sisaHari[min], sisaHari[i]
            namaPemilik[i], namaPemilik[min] = namaPemilik[min], namaPemilik[i]

def tanggalDescending(namaBarang, tanggal, sisaHari, namaPemilik):
    for i in range (0, len(tanggal)) :
        min = i
        for j in range (i, len(tanggal)) :
            if tanggal[min] < tanggal[j] :
                min = j
            tanggal[i], tanggal[min] = tanggal[min], tanggal[i]
            namaBarang[i], namaBarang[min] = namaBarang[min], namaBarang[i]
            sisaHari[i], sisaHari[min] = sisaHari[min], sisaHari[i]
            namaPemilik[i], namaPemilik[min] = namaPemilik[min], namaPemilik[i]
   
   
def inputBarang(jumlahBarang):
    # 3. Listing Nama Barang dan Tanggal
    for j in range(0, jumlahBarang):
        
        inputBarang = input("\nMasukkan Nama Barang : ")
        namaBarang.append(inputBarang) 
    
        inputTanggal = input("Masukkan Tanggal (yyyy-mm-dd): ")      
        year, month, day = map(int, inputTanggal.split('-'))
        konversiTanggal = datetime.date(year, month, day)
        tanggal.append(konversiTanggal)
        
        hariIni = datetime.date.today()
        hariSisa = konversiTanggal - hariIni
        sisaHari.append(hariSisa)
        
        inputNama = input("Masukkan Nama Pemilik : ")
        namaPemilik.append(inputNama) 
    
    
def urutkan():
    # 4. Mengurutkan Tanggal
    kondisi = True

    while kondisi:
        
        urutkan = input("\nApakah Anda ingin mengurutkan? [y/n] : ")
        
        if urutkan == "y":
            print("\n1. Ascending")
            print("2. Descending")
            pilihan = input("Ingin mengurutkan secara Ascending atau Descending ? : ")
            
            if pilihan == "1":
                tanggalAscending(namaBarang, tanggal, sisaHari, namaPemilik) # sorting tanggal secara Ascending
                kondisi = False
            elif pilihan == "2":
                tanggalDescending(namaBarang, tanggal, sisaHari, namaPemilik) # sorting tanggal secara Descending 
                kondisi = False
            else :
                print("Mohon input sesuai pilihan [y/n]")
                continue   
            
        elif urutkan == "n":
            break
        
        else :
            print("Mohon input sesuai pilihan [y/n]")
            continue
        
        print()
        
        tampilan(namaBarang, tanggal, sisaHari) # Menampilkan hasil sorting. 

# 1. Membuat wadah kosong berupa List untuk daftar Nama Barang dan Tanggal
namaPemilik = []
namaBarang = []
tanggal = []
sisaHari = []

kondisi2 = True
 
while kondisi2:
    # 2. Tampilan Awal
    jumlahBarang = int(input("\nMasukkan banyaknya barang yang ingin diinput : "))
    inputBarang(jumlahBarang)
    urutkan() 
    tanya = input("\nApa ingin menambahkan? [y/n] : ")
    if tanya == "y":
        continue
    elif tanya == "n":
        print("\nProgram Berakhir, Terima Kasih")
        break
    else:
        print("Mohon input sesuai pilihan [y/n]")
        continue